export const teams = {
     "Arizona Cardinals": "/logos/cardinals.gif",
     "Atlanta Falcons": "/logos/falcons.gif",
     "Baltimore Ravens": "/logos/ravens.gif",
     "Buffalo Bills": "/logos/bills.gif",
     "Carolina Panthers": "/logos/panthers.gif",
     "Chicago Bears": "/logos/bears.gif",
     "Cincinnati Bengals": "/logos/bengals.gif",
     "Cleveland Browns": "/logos/browns.gif",
     "Dallas Cowboys": "/logos/cowboys.gif",
     "Denver Broncos": "/logos/broncos.gif",
     "Detroit Lions": "/logos/lions.gif",
     "Green Bay Packers": "/logos/packers.gif",
     "Houston Texans": "/logos/texans.gif",
     "Indianapolis Colts": "/logos/colts.gif",
     "Jacksonville Jaguars": "/logos/jaguars.gif",
     "Kansas City Chiefs": "/logos/chiefs.gif",
     "Las Vegas Raiders": "/logos/raiders.gif",
     "Los Angeles Chargers": "/logos/chargers.gif",
     "Los Angeles Rams": "/logos/rams.gif",
     "Miami Dolphins": "/logos/dolphins.gif",
     "Minnesota Vikings": "/logos/vikings.gif",
     "New England Patriots": "/logos/patriots.gif",
     "New Orleans Saints": "/logos/saints.gif",
     "New York Giants": "/logos/giants.gif",
     "New York Jets": "/logos/jets.gif",
     "Philadelphia Eagles": "/logos/eagles.gif",
     "Pittsburgh Steelers": "/logos/steelers.gif",
     "San Francisco 49ers": "/logos/49ers.gif",
     "Seattle Seahawks": "/logos/seahawks.gif",
     "Tampa Bay Buccaneers": "/logos/buccaneers.gif",
     "Tennessee Titans": "/logos/titans.gif",
     "Washington Commanders": "/logos/commanders.gif",
};

export const seeds = {
     1: "/logos/1.png",
     2: "/logos/2.png",
     3: "/logos/3.png",
     4: "/logos/4.png",
     5: "/logos/5.png",
     6: "/logos/6.png",
     7: "/logos/7.png",
};